<a href="https://colab.research.google.com/github/jhbuitragoq-oss/analiticadedatosuq/blob/main/PARCIAL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# PARCIAL 1 ELECTIVA HECHO POR JUNIOR HERNEY BUITRAGO Y LAURA MELISSA GIRALDO

In [1]:
#IMPORTA LIBRE
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
#Obtener directorio de trabajo actual
current_working_directory = Path.cwd()
current_working_directory

PosixPath('/content')

In [3]:
#Caracteristicas generales, seguridad social en salud y educacion

# Links a los conjuntos de datos
url_cgsse ='https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV'
url_ocupados = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
url_ft ='https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'
url_desocupados = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'


# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';',
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados,encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

In [4]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67851,20250626,6,2025,8283060,1,1,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
67852,20250626,6,2025,8283060,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
67853,20250626,6,2025,8283062,1,1,1,10,94.0,1,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
67854,20250626,6,2025,8283062,1,2,1,10,94.0,1,...,2.0,NaN,3.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0
67855,20250626,6,2025,8283062,1,3,1,10,94.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0

In [15]:
df_ft

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20250626,6,2025,8238974,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250626,6,2025,8238974,1,2,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250626,6,2025,8238975,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20250626,6,2025,8238975,1,2,1,50,NaN,2,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250626,6,2025,8238975,1,3,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54445,20250626,6,2025,8283060,1,1,1,50,88.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54446,20250626,6,2025,8283060,1,2,1,50,88.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54447,20250626,6,2025,8283062,1,1,1,50,94.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54448,20250626,6,2025,8283062,1,2,1,50,94.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54449,20250626,6,2025,8283062,1,3,1,50,94.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_ocupados

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250626,6,2025,8238974,1,1,1,60,NaN,2,...,3,NaN,3.0,3,NaN,1,950000.0,1,113,6111
1,20250626,6,2025,8238974,1,2,1,60,NaN,2,...,3,NaN,4.0,5,NaN,1,NaN,1,113,6111
2,20250626,6,2025,8238975,1,1,1,60,NaN,2,...,3,NaN,10.0,3,NaN,1,700000.0,1,113,6114
3,20250626,6,2025,8238975,1,3,1,60,NaN,2,...,3,NaN,10.0,3,NaN,1,2000000.0,1,145,6122
4,20250626,6,2025,8238976,1,1,1,60,NaN,2,...,14,NaN,NaN,8,NaN,1,600000.0,1,122,6112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29701,20250626,6,2025,8283057,1,3,1,60,41.0,1,...,8,NaN,25.0,5,NaN,1,3800000.0,85,8544,2310
29702,20250625,6,2025,8283058,1,1,1,60,NaN,1,...,14,NaN,NaN,2,NaN,1,3000000.0,71,7111,2161
29703,20250625,6,2025,8283058,1,2,1,60,NaN,1,...,3,NaN,10.0,1,NaN,1,1500000.0,47,4752,1420
29704,20250626,6,2025,8283060,1,2,1,60,88.0,1,...,3,NaN,10.0,8,NaN,1,500000.0,56,5619,7512
29705,20250626,6,2025,8283062,1,1,1,60,94.0,1,...,9,NaN,300.0,8,NaN,1,900000.0,3,312,6222

In [17]:
df_desocupados

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P7360,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4
0,20250626,6,2025,8238975,1,2,1,70,NaN,2,...,1.0,2.0,2,NaN,2,NaN,.,6112,1.0,0123
1,20250626,6,2025,8238978,1,1,1,70,NaN,2,...,1.0,2.0,2,NaN,2,NaN,.,9211,1.0,0161
2,20250626,6,2025,8238980,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
3,20250626,6,2025,8238981,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
4,20250626,6,2025,8238983,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24739,20250626,6,2025,8283056,1,1,1,70,27.0,1,...,10.0,2.0,3,NaN,2,NaN,.,2341,85.0,8530
24740,20250626,6,2025,8283059,1,1,1,70,76.0,1,...,6.0,2.0,2,NaN,2,NaN,5223,5113,55.0,5511
24741,20250626,6,2025,8283060,1,1,1,70,88.0,1,...,9.0,2.0,2,NaN,2,NaN,.,9334,47.0,4711
24742,20250626,6,2025,8283062,1,2,1,70,94.0,1,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
24743,20250626,6,2025,8283062,1,3,1,70,94.0,1,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.

In [5]:
# 1) POBLACION TOTAL = La población total corresponde al número total de registros en la base de datos.
df_cgsse['FEX_C18'].sum()

np.float64(52045001.000009045)

In [7]:
# POBLACION EN EDAD DE TRABAJAR = Se filtran las personas con edad mayor o igual a 15 años, que corresponden a la población en edad de trabajar.
PET = df_cgsse[df_cgsse['P6040']>=15]['FEX_C18'].sum()
print(f'Poblacion en edad de trabajar: {PET}')

Poblacion en edad de trabajar: 40653416.00000409

In [8]:
# POBLACION QUE NO ESTA EN EDAD DE TRABAJAR = Se filtran las personas menores de 15 años y se suma el factor de expansión para estimar la población total representada.
PNET = df_cgsse[df_cgsse['P6040']<15]['FEX_C18'].sum()
print(f'Poblacion que no está en  edad de trabajar: {int(PNET)}')

Poblacion que no está en  edad de trabajar: 11391585

In [12]:
# POBLACION ECONOMICAMENTE ACTIVA E INACTIVA = La PEA incluye las personas que estan trajando y estan buscando trabajo y la PEI Son las personas que no trabajan ni buscan trabajo.
PEA = df_ft[df_ft['FT']==1]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa: {PEA}')

PEI = df_ft[df_ft['FFT']==1]['FEX_C18'].sum()
print(f'Poblacion Economicamente inactiva: {int(PEI)}')

Poblacion Economicamente Activa: 25974846.223567855
Poblacion Economicamente inactiva: 14678569

In [19]:
# TASA OCUPACION = La tasa de ocupación muestra qué porcentaje de la población en edad de trabajar está ocupada.
O = df_ocupados['FEX_C18'].sum()
print(f'Poblacion ocupada: {int(O)}')

PET = df_ft['FEX_C18'].sum()
print(f'Poblacion En edad de trabajar : {int(PET)}')

TO = O/PET
print(f'Tasa de Ocupacion: {TO:.2%}')

Poblacion ocupada: 23752952
Poblacion En edad de trabajar : 40653416
Tasa de Ocupacion: 58.43%

In [22]:
# TASA DE DESEMPLO = La tasa de desempleo mide el porcentaje de la población activa que no tiene trabajo pero lo está buscando.
D = df_desocupados[df_desocupados['DSI']==1]['FEX_C18'].sum()
print(f'Poblacion Desempleada: {D}')

TD = D/PEA
print(f'Tasa de Desempleo: {TD*100}%')

Poblacion Desempleada: 2221893.563312005
Tasa de Desempleo: 8.554020086155527%

In [24]:
# 2)Calcule las tasas de desempleo para hombres y mujeres en Risaralda, Caldas , Tolima y Quindío. ¿Cuál es el departamento con mayor y menor tasa de desempleo de los 4 ?
df_d = pd.merge(df_desocupados, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']],
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

df_ft = pd.merge(df_ft, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']],
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [110]:
#QUINDIO
# 1. Calcular cantidad de hombres desempleados en el QUINDIO
HDQ = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==63) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Quindio: {HDQ}')

# 2. Calcular cantidad de hombres en la PEA del QUINDIO
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el quindío: {PEAHQ}')

# 3. Calcular la tasa de desempleo en hombres del QUINDIO
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del quindío: {TDHQ*100}%')

Hombres Desempleados en el Quindio: 17869.520960767004
Poblacion Economicamente Activa de hombres en el quindío: 174625.87195169798
Tasa de Desempleo en hombres del quindío: 10.233031773040919%

In [26]:
# 1. Calcular cantidad de MUJERES desempleadas en el QUINDIO
MDQ = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==63) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en el Quindio: {MDQ}')

# 2. Calcular cantidad de mujeres en la PEA del QUINDIO
PEAMQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en el quindío: {PEAMQ}')

# 3. Calcular la tasa de desempleo en mujeres del QUINDIO
TDMQ = MDQ/PEAMQ
print(f'Tasa de Desempleo en mujeres del quindío: {TDMQ*100}%')

Mujeres Desempleadas en el Quindio: 10618.534945967001
Poblacion Economicamente Activa de mujeres en el quindío: 116885.879263648
Tasa de Desempleo en mujeres del quindío: 9.084531863781265%

In [42]:
# TASA DESEMPLEO QUINDIO
DTQ = HDQ + MDQ
PEATQ = PEAHQ + PEAMQ

TDQ = DTQ / PEATQ

print(f"Tasa de desempleo total Quindío: {TDQ*100:.2f}%")

Tasa de desempleo total Quindío: 9.77%

In [36]:
#RISARALDA
# Hombres desempleados en RISARALDA
HDR = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==66) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleadas en Risaraldoa: {HDR}')

# Hombres en la PEA
PEAHR = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==1)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de Hombres en Risaralda: {PEAHR}')

# Tasa desempleo hombres
TDHR = HDR/PEAHR
print(f'Tasa de desempleo hombres Risaralda: {TDHR*100}%')

Hombres Desempleadas en Risaraldoa: 18000.60370715
Poblacion Economicamente Activa de Hombres en Risaralda: 296342.328368219
Tasa de desempleo hombres Risaralda: 6.074260064793518%

In [34]:
# 1. Calcular cantidad de MUJERES desempleadas en Risaralda
MDR = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==66) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en el Risaralda: {MDR}')

# 2. Calcular cantidad de mujeres en la PEA del Risaraldo
PEAMR = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en el Risaralda: {PEAMR}')

# 3. Calcular la tasa de desempleo en mujeres del Risaralda
TDMR = MDR/PEAMR
print(f'Tasa de Desempleo en mujeres del Risaralda: {TDMR*100}%')

Mujeres Desempleadas en el Risaralda: 21676.799766712
Poblacion Economicamente Activa de mujeres en el Risaralda: 203157.903399127
Tasa de Desempleo en mujeres del Risaralda: 10.669926891362644%

In [44]:
# TASA DESEMPLEO RISARALDA
DTR = HDR + MDR
PEATR = PEAHR + PEAMR

TDR = DTR / PEATR

print(f"Tasa de desempleo total Risaralda: {TDR*100:.2f}%")

Tasa de desempleo total Risaralda: 7.94%

In [38]:
# CALDAS
# Hombres desempleados
HDC = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==17) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleadas en Caldas: {HDC}')

# Hombres en PEA
PEAHC = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==17) & (df_ft['P3271']==1)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de Hombres en Caldas: {PEAHC}')

TDHC = HDC/PEAHC
print(f'Tasa de desempleo hombres Caldas: {TDHC*100}%')

Hombres Desempleadas en Caldas: 18226.160047418998
Poblacion Economicamente Activa de Hombres en Caldas: 326447.467769983
Tasa de desempleo hombres Caldas: 5.5831831601957065%

In [39]:
# Mujeres desempleadas
MDC = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==17) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en Caldas: {MDC}')

# Mujeres PEA
PEAMC = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==17) & (df_ft['P3271']==2)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en Caldas: {PEAMC}')

TDMC = MDC/PEAMC
print(f'Tasa de desempleo mujeres Caldas: {TDMC*100}%')

Mujeres Desempleadas en Caldas: 17214.491449226003
Poblacion Economicamente Activa de mujeres en Caldas: 224206.533775
Tasa de desempleo mujeres Caldas: 7.677961547053494%

In [45]:
#TASA DESEMPLEO CALDAS
DTC = HDC + MDC
PEATC = PEAHC + PEAMC

TDC = DTC / PEATC

print(f"Tasa de desempleo total Caldas: {TDC*100:.2f}%")

Tasa de desempleo total Caldas: 6.44%

In [40]:
#TOLIMA
# Hombres desempleados
HDT = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==73) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleadas en Tolima: {HDT}')

# Hombres PEA
PEAHT = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==73) & (df_ft['P3271']==1)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de Hombres en Tolima: {PEAHT}')

TDHT = HDT/PEAHT
print(f'Tasa de desempleo hombres Tolima: {TDHT*100}%')

Hombres Desempleadas en Tolima: 28255.96613253
Poblacion Economicamente Activa de Hombres en Tolima: 391325.28931057
Tasa de desempleo hombres Tolima: 7.220582697916321%

In [41]:
# Mujeres desempleadas
MDT = df_desocupados[(df_d['DSI']==1) & (df_d['DPTO']==73) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en Tolima: {MDT}')

# Mujeres PEA
PEAMT = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==73) & (df_ft['P3271']==2)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en Tolima: {PEAMC}')

TDMT = MDT/PEAMT
print(f'Tasa de desempleo mujeres Tolima: {TDMT*100}%')

Mujeres Desempleadas en Tolima: 52100.16756370999
Poblacion Economicamente Activa de mujeres en Tolima: 224206.533775
Tasa de desempleo mujeres Tolima: 19.20274740190366%

In [46]:
# TASA DESEMPLO TOLIMA
DTT = HDT + MDT
PEATT = PEAHT + PEAMT

TDT = DTT / PEATT

print(f"Tasa de desempleo total Tolima: {TDT*100:.2f}%")

Tasa de desempleo total Tolima: 12.13%

In [ ]:
#RESPUESTA = A partir de los calculso realizados se identifica qeu el Departamento con mayor tasa de desempleo es Tolima con 12.13% y el de Departamento con menor tasa de desempleo es Caldas con 6.44%

In [ ]:
# 3) ¿cual es el grupo de edad con mayor y menor tasa de desempleo (indicar en cada departamento el grupo de de edad  con mayor y menor tasa de desempleo) ?

In [100]:
#Segmento de 18 a 24 años de edad QUINDIO

# 1. Calcular cantidad personas desempleadas entre los 18 - 24
D1824 = df_desocupados[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 18 - 24 años: {D1824}')

# 2. Calcular cantidad personas en la PEA entre los 18 - 24
PEA1824 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 18 - 24 años: {PEA1824}')

# 3. Calcular la tasa de desempleo en personas entre los 18 - 24 del quindío
TD1824 = D1824/PEA1824
print(f'Tasa de Desempleo en personas entre los 18 - 24 del quindío: {TD1824*100}%')

Personas Desempleadas en el quindío entre los 18 - 24 años: 3819.2724449800003
Poblacion Economicamente Activa en el quindío entre los 18 - 24 años: 29912.663758397
Tasa de Desempleo en personas entre los 18 - 24 del quindío: 12.768078683423386%

In [101]:
# QUINDIO
# Segmento de 24 a 30 años QUINDIO

# 1. Personas desempleadas entre 24 - 30
D2430 = df_desocupados[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 24 - 30 años: {D2430}')

# 2. Personas en la PEA entre 24 - 30
PEA2430 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 24 - 30 años: {PEA2430}')

# 3. Tasa de desempleo
TD2430 = D2430/PEA2430
print(f'Tasa de Desempleo en personas entre los 24 - 30 del quindío: {TD2430*100}%')

Personas Desempleadas en el quindío entre los 24 - 30 años: 7008.068900358
Poblacion Economicamente Activa en el quindío entre los 24 - 30 años: 51117.425383347
Tasa de Desempleo en personas entre los 24 - 30 del quindío: 13.709745449427672%

In [102]:
# Segmento de 30 a 40 años QUINDIO

D3040 = df_desocupados[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 30 - 40 años: {D3040}')

PEA3040 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 30 - 40 años: {PEA3040}')

TD3040 = D3040/PEA3040
print(f'Tasa de Desempleo en personas entre los 30 - 40 del quindío: {TD3040*100}%')

Personas Desempleadas en el quindío entre los 30 - 40 años: 7015.512022579001
Poblacion Economicamente Activa en el quindío entre los 30 - 40 años: 72731.96687714598
Tasa de Desempleo en personas entre los 30 - 40 del quindío: 9.645706453159914%

In [51]:
# Segmento de 40 a 50 años QUINDIO

D4050 = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 40 - 50 años: {D4050}')

PEA4050 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 40 - 50 años: {PEA4050}')

TD4050 = D4050/PEA4050
print(f'Tasa de Desempleo en personas entre los 40 - 50 del quindío: {TD4050*100}%')

Personas Desempleadas en el quindío entre los 40 - 50 años: 4416.562673204001
Poblacion Economicamente Activa en el quindío entre los 40 - 50 años: 70586.28939453498
Tasa de Desempleo en personas entre los 40 - 50 del quindío: 6.256969605695048%

In [52]:
# Segmento de 60 años en adelante QUINDIO

D60 = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío de 60 años o más: {D60}')

PEA60 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío de 60 años o más: {PEA60}')

TD60 = D60/PEA60
print(f'Tasa de Desempleo en personas de 60 años o más del quindío: {TD60*100}%')

Personas Desempleadas en el quindío de 60 años o más: 4297.130465619
Poblacion Economicamente Activa en el quindío de 60 años o más: 41690.707895215004
Tasa de Desempleo en personas de 60 años o más del quindío: 10.307165991086942%

In [53]:
# RISARALDA
# Segmento de 18 a 24 años RISARALDA

D1824R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==66)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Risaralda entre los 18 - 24 años: {D1824R}')

PEA1824R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==66)]['FEX_C18'].sum()
print(f'PEA en Risaralda entre los 18 - 24 años: {PEA1824R}')

TD1824R = D1824R/PEA1824R
print(f'Tasa de Desempleo en Risaralda entre los 18 - 24: {TD1824R*100}%')

Personas Desempleadas en Risaralda entre los 18 - 24 años: 9385.755003442
PEA en Risaralda entre los 18 - 24 años: 63454.922070486005
Tasa de Desempleo en Risaralda entre los 18 - 24: 14.79121665773423%

In [54]:
# Segmento de 24 a 30 años RISARALDA
D2430R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==66)]['FEX_C18'].sum()
print(f'Desempleados Risaralda 24-30: {D2430R}')

PEA2430R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==66)]['FEX_C18'].sum()
print(f'PEA Risaralda 24-30: {PEA2430R}')

TD2430R = D2430R/PEA2430R
print(f'Tasa desempleo Risaralda 24-30: {TD2430R*100}%')

Desempleados Risaralda 24-30: 10504.69809363
PEA Risaralda 24-30: 90684.88337600001
Tasa desempleo Risaralda 24-30: 11.5837366742538%

In [55]:

D3040R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==66)]['FEX_C18'].sum()

PEA3040R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD3040R = D3040R/PEA3040R
print(f'Tasa desempleo Risaralda 30-40: {TD3040R*100}%')

Tasa desempleo Risaralda 30-40: 6.447452329705859%

In [56]:
# Segmento de 40 a 50 años RISARALDA
D4050R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==66)]['FEX_C18'].sum()

PEA4050R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD4050R = D4050R/PEA4050R
print(f'Tasa desempleo Risaralda 40-50: {TD4050R*100}%')

Tasa desempleo Risaralda 40-50: 7.3356816001245955%

In [57]:
# Segmento de 60 O MAS RISARALDA
D60R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==66)]['FEX_C18'].sum()

PEA60R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD60R = D60R/PEA60R
print(f'Tasa desempleo Risaralda 60+: {TD60R*100}%')

Tasa desempleo Risaralda 60+: 3.6398607318240614%

In [58]:
# CALDAS
# Segmento de 18 a 24 años CALDAS

D1824C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==17)]['FEX_C18'].sum()

PEA1824C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD1824C = D1824C/PEA1824C
print(f'Tasa desempleo Caldas 18-24: {TD1824C*100}%')

Tasa desempleo Caldas 18-24: 9.344949005517167%

In [59]:
# Segmento de 24 a 30 años CALDAS

D2430C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==17)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Caldas entre los 24 - 30 años: {D2430C}')

PEA2430C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==17)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Caldas entre los 24 - 30 años: {PEA2430C}')

TD2430C = D2430C/PEA2430C
print(f'Tasa de Desempleo en personas entre los 24 - 30 de Caldas: {TD2430C*100}%')

Personas Desempleadas en Caldas entre los 24 - 30 años: 6090.488353998
Poblacion Economicamente Activa en Caldas entre los 24 - 30 años: 94541.70353229
Tasa de Desempleo en personas entre los 24 - 30 de Caldas: 6.442118267858205%

In [60]:
# Segmento de 30 a 40 años CALDAS

D3040C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==17)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Caldas entre los 30 - 40 años: {D3040C}')

PEA3040C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==17)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Caldas entre los 30 - 40 años: {PEA3040C}')

TD3040C = D3040C/PEA3040C
print(f'Tasa de Desempleo en personas entre los 30 - 40 de Caldas: {TD3040C*100}%')

Personas Desempleadas en Caldas entre los 30 - 40 años: 7691.5534119310005
Poblacion Economicamente Activa en Caldas entre los 30 - 40 años: 134487.41843531598
Tasa de Desempleo en personas entre los 30 - 40 de Caldas: 5.719162060970324%

In [61]:
# Segmento de 40 a 50 años CALDAS

D4050C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==17)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Caldas entre los 40 - 50 años: {D4050C}')

PEA4050C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==17)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Caldas entre los 40 - 50 años: {PEA4050C}')

TD4050C = D4050C/PEA4050C
print(f'Tasa de Desempleo en personas entre los 40 - 50 de Caldas: {TD4050C*100}%')

Personas Desempleadas en Caldas entre los 40 - 50 años: 6318.584371157001
Poblacion Economicamente Activa en Caldas entre los 40 - 50 años: 123334.19349942802
Tasa de Desempleo en personas entre los 40 - 50 de Caldas: 5.123140786732679%

In [62]:
# Segmento de 60 años o más CALDAS

D60C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==17)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Caldas de 60 años o más: {D60C}')

PEA60C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==17)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Caldas de 60 años o más: {PEA60C}')

TD60C = D60C/PEA60C
print(f'Tasa de Desempleo en personas de 60 años o más de Caldas: {TD60C*100}%')

Personas Desempleadas en Caldas de 60 años o más: 2543.690331052
Poblacion Economicamente Activa en Caldas de 60 años o más: 62637.207145629
Tasa de Desempleo en personas de 60 años o más de Caldas: 4.060989381499756%

In [63]:
# TOLIMA
# Segmento de 18 a 24 años TOLIMA

D1824T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==73)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Tolima entre los 18 - 24 años: {D1824T}')

PEA1824T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==73)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Tolima entre los 18 - 24 años: {PEA1824T}')

TD1824T = D1824T/PEA1824T
print(f'Tasa de Desempleo en personas entre los 18 - 24 de Tolima: {TD1824T*100}%')

Personas Desempleadas en Tolima entre los 18 - 24 años: 15908.42272112
Poblacion Economicamente Activa en Tolima entre los 18 - 24 años: 80276.38281808
Tasa de Desempleo en personas entre los 18 - 24 de Tolima: 19.817064699055017%

In [64]:
# Segmento de 24 a 30 años TOLIMA

D2430T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==73)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Tolima entre los 24 - 30 años: {D2430T}')

PEA2430T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==73)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Tolima entre los 24 - 30 años: {PEA2430T}')

TD2430T = D2430T/PEA2430T
print(f'Tasa de Desempleo en personas entre los 24 - 30 de Tolima: {TD2430T*100}%')

Personas Desempleadas en Tolima entre los 24 - 30 años: 12039.076700790001
Poblacion Economicamente Activa en Tolima entre los 24 - 30 años: 86718.36533803001
Tasa de Desempleo en personas entre los 24 - 30 de Tolima: 13.882960839796077%

In [65]:
# Segmento de 30 a 40 años TOLIMA

D3040T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==73)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Tolima entre los 30 - 40 años: {D3040T}')

PEA3040T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==73)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Tolima entre los 30 - 40 años: {PEA3040T}')

TD3040T = D3040T/PEA3040T
print(f'Tasa de Desempleo en personas entre los 30 - 40 de Tolima: {TD3040T*100}%')

Personas Desempleadas en Tolima entre los 30 - 40 años: 18987.559043110003
Poblacion Economicamente Activa en Tolima entre los 30 - 40 años: 155035.56353474
Tasa de Desempleo en personas entre los 30 - 40 de Tolima: 12.247228061873246%

In [66]:
# Segmento de 40 a 50 años TOLIMA

D4050T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==73)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Tolima entre los 40 - 50 años: {D4050T}')

PEA4050T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==73)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Tolima entre los 40 - 50 años: {PEA4050T}')

TD4050T = D4050T/PEA4050T
print(f'Tasa de Desempleo en personas entre los 40 - 50 de Tolima: {TD4050T*100}%')

Personas Desempleadas en Tolima entre los 40 - 50 años: 12768.45231577
Poblacion Economicamente Activa en Tolima entre los 40 - 50 años: 147765.20025582
Tasa de Desempleo en personas entre los 40 - 50 de Tolima: 8.641041526465289%

In [67]:
# Segmento de 60 años o más TOLIMA

D60T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==73)]['FEX_C18'].sum()
print(f'Personas Desempleadas en Tolima de 60 años o más: {D60T}')

PEA60T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==73)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en Tolima de 60 años o más: {PEA60T}')

TD60T = D60T/PEA60T
print(f'Tasa de Desempleo en personas de 60 años o más de Tolima: {TD60T*100}%')

Personas Desempleadas en Tolima de 60 años o más: 9913.257434480001
Poblacion Economicamente Activa en Tolima de 60 años o más: 104806.45873117
Tasa de Desempleo en personas de 60 años o más de Tolima: 9.458632182113549%

In [ ]:
#RESPUESTA = GRUPO DE EDAD MAYOR TASA DESEMPLEO
#QUINDIO ES 24 - 30: 13.709745449427672% Y MENOR DE 40 - 50: 6.256969605695048%.
#RISARALDA MAYOR ES 18 - 24: 14.79121665773423% Y MENOR 60+: 3.6398607318240614%.
#CALDAS ES 18-24: 9.344949005517167% Y MENOR 60 años o más: 4.060989381499756%
#TOLIMA 18 - 24 de Tolima: 19.817064699055017% y MENOR 40 - 50: 8.641041526465289%

In [68]:
# 4) Entre Risaralda, Caldas , Tolima y Quindío, cuál es el departamento con menor tasa de desempleo de mujeres entre los 18 y los 25 años ?
# MUJERES ENTRE 18 Y 25 AÑOS

# QUINDIO
MD1825Q = df_d[(df_d['DSI']==1) & (df_d['P3271']==2) & (df_d['P6040']>=18) & (df_d['P6040']<=25) & (df_d['DPTO']==63)]['FEX_C18'].sum()

PEA1825Q = df_ft[(df_ft['FT']==1) & (df_ft['P3271']==2) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==63)]['FEX_C18'].sum()

TD1825Q = MD1825Q / PEA1825Q
print(f"Tasa desempleo mujeres 18-25 Quindío: {TD1825Q*100:.2f}%")

Tasa desempleo mujeres 18-25 Quindío: 7.47%

In [69]:
# RISARALDA
MD1825R = df_d[(df_d['DSI']==1) & (df_d['P3271']==2) & (df_d['P6040']>=18) & (df_d['P6040']<=25) & (df_d['DPTO']==66)]['FEX_C18'].sum()

PEA1825R = df_ft[(df_ft['FT']==1) & (df_ft['P3271']==2) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD1825R = MD1825R / PEA1825R
print(f"Tasa desempleo mujeres 18-25 Risaralda: {TD1825R*100:.2f}%")

Tasa desempleo mujeres 18-25 Risaralda: 22.99%

In [70]:
# CALDAS
MD1825C = df_d[(df_d['DSI']==1) & (df_d['P3271']==2) & (df_d['P6040']>=18) & (df_d['P6040']<=25) & (df_d['DPTO']==17)]['FEX_C18'].sum()

PEA1825C = df_ft[(df_ft['FT']==1) & (df_ft['P3271']==2) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD1825C = MD1825C / PEA1825C
print(f"Tasa desempleo mujeres 18-25 Caldas: {TD1825C*100:.2f}%")

Tasa desempleo mujeres 18-25 Caldas: 14.50%

In [71]:
# TOLIMA
MD1825T = df_d[(df_d['DSI']==1) & (df_d['P3271']==2) & (df_d['P6040']>=18) & (df_d['P6040']<=25) & (df_d['DPTO']==73)]['FEX_C18'].sum()

PEA1825T = df_ft[(df_ft['FT']==1) & (df_ft['P3271']==2) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

TD1825T = MD1825T / PEA1825T
print(f"Tasa desempleo mujeres 18-25 Tolima: {TD1825T*100:.2f}%")

Tasa desempleo mujeres 18-25 Tolima: 21.38%

In [ ]:
# RESPUESTA = EL DEPARTAMENTO CON MENOR TASA DE DESEMPLEO DE MUJERES ENTRE LOS 18 Y 25 AÑOS ES EL QUINDIO CON 7.47%

In [80]:
#5) ¿Cuántos hombres y mujeres hay en edad de trabajar en el quindio ? ¿Qué porcentaje de la población total representan ?

# 1. Población total del Quindío
PTQ = df_cgsse[(df_cgsse['DPTO']==63)]['FEX_C18'].sum()
print(f'Población total del Quindío: {PTQ}')

Población total del Quindío: 603068.649439007

In [82]:
# 2. Hombres en edad de trabajar (15 o más) en Quindío
HETQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==1) & (df_cgsse['P6040']>=15)]['FEX_C18'].sum()

print(f'Hombres en edad de trabajar en el Quindío: {HETQ}')

Hombres en edad de trabajar en el Quindío: 247037.510834763

In [83]:
# 3. Mujeres en edad de trabajar (15 o más) en Quindío
METQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==2) & (df_cgsse['P6040']>=15)]['FEX_C18'].sum()

print(f'Mujeres en edad de trabajar en el Quindío: {METQ}')

Mujeres en edad de trabajar en el Quindío: 261387.92755063402

In [84]:
# 4. Porcentaje que representan

PHETQ = (HETQ / PTQ) * 100
PMETQ = (METQ / PTQ) * 100

print(f'Porcentaje hombres en edad de trabajar en Quindío: {PHETQ:.2f}%')
print(f'Porcentaje mujeres en edad de trabajar en Quindío: {PMETQ:.2f}%')

Porcentaje hombres en edad de trabajar en Quindío: 40.96%
Porcentaje mujeres en edad de trabajar en Quindío: 43.34%

In [ ]:
#RESPUESTA = filtró la población del departamento del Quindío utilizando el código DPTO = 63. Posteriormente se identificaron las personas en edad de trabajar, considerando aquellas con 15 años o más según la variable P6040. Luego se separó la población por sexo utilizando la variable P3271, donde el valor 1 corresponde a hombres y 2 a mujeres. Finalmente se calculó el porcentaje que representan los hombres y mujeres en edad de trabajar respecto a la población total del departamento.

In [85]:
#6) ¿Qué porcentaje de la población del Tolima está en edad de trabajar ?
#POBLACION TOTAL TOLIMA
PTT = df_cgsse[(df_cgsse['DPTO']==73)]['FEX_C18'].sum()

print(f'Población total del Tolima: {PTT}')

Población total del Tolima: 1411965.04428173

In [86]:
#POBLACION EN EDAD DE TRABAJAR
PETT = df_cgsse[(df_cgsse['DPTO']==73) & (df_cgsse['P6040']>=15)]['FEX_C18'].sum()

print(f'Población en edad de trabajar en Tolima: {PETT}')

Población en edad de trabajar en Tolima: 1087359.08383866

In [87]:
#PORCENTAJE DE POBLACION EN EDAD DE TRABAJAR
PORPETT = (PETT / PTT) * 100
print(f'Porcentaje de la población del Tolima en edad de trabajar: {PORPETT:.2f}%')

Porcentaje de la población del Tolima en edad de trabajar: 77.01%

In [ ]:
#RESPUESTA = se filtraron los registros correspondientes a este departamento utilizando el código DPTO = 73. Posteriormente se seleccionaron las personas con 15 años o más utilizando la variable P6040, que representa la edad de los individuos. Finalmente se dividió la población en edad de trabajar entre la población total del Tolima y se multiplicó por 100 para obtener el porcentaje.

In [88]:
# 7)¿ Qué porcentaje de la población de Risaralda es población económicamente inactiva ?
# Población total de Risaralda
PTR = df_cgsse[(df_cgsse['DPTO']==66)]['FEX_C18'].sum()

print(f'Población total de Risaralda: {PTR}')

Población total de Risaralda: 1025240.9423573611

In [ ]:
# Población económicamente inactiva
PEIR = df_ft[(df_ft['DPTO']==66) & (df_ft['FFT']==1)]['']FEX_C18.sum()

print(f'Población económicamente inactiva en Risaralda: {PEIR}')

Población económicamente inactiva en Risaralda: 332743.42055744905

In [91]:
# Porcentaje de población económicamente inactiva
PORPEIR = (PEIR / PTR) * 100

print(f'Porcentaje de población económicamente inactiva en Risaralda: {PORPEIR:.2f}%')

Porcentaje de población económicamente inactiva en Risaralda: 32.46%

In [ ]:
# RESPUESTA = Para calcular el porcentaje de población económicamente inactiva en el departamento de Risaralda se filtraron los registros correspondientes a este departamento utilizando el código DPTO = 66. Posteriormente se identificaron las personas clasificadas como población económicamente inactiva mediante la variable FFT. Luego se sumó el factor de expansión FEX_C18 para estimar el total de personas en esta condición. Finalmente, este valor se dividió entre la población total del departamento y se multiplicó por 100 para obtener el porcentaje

In [ ]:
# RESPUESTA = Para calcular el número de personas desempleadas entre 18 y 30 años en el departamento del Quindío, utilizamos el código DPTO = 63. Posteriormente se seleccionaron las personas clasificadas como desempleadas mediante la variable DSI = 1 y se restringió el análisis al rango de edad entre 18 y 30 años utilizando la variable P6040. Finalmente se sumó el factor de expansión FEX_C18 para estimar el número total de personas en esta condición

In [115]:
# 8) ¿Cuántas personas hay en el Quindío en condición de desempleo entre los 18 y los 30 años ?
# Personas desempleadas entre 18 y 30 años en el Quindío
D1830 = df_desocupados[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=30) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 18 - 30 años: {D1830}')

Personas Desempleadas en el quindío entre los 18 - 30 años: 9479.632579867999

In [97]:
# 9) ¿Cuántas personas hay ocupadas en el departamento del Tolima , cuyas edades están entre los 20 y los 25 años , qué porcentaje de la población total del Tolima representan ?
#Población total del Tolima
PTT = df_cgsse[(df_cgsse['DPTO']==73)]['FEX_C18'].sum()

print(f'Población total del Tolima: {PTT}')

Población total del Tolima: 1411965.04428173

In [122]:
#OCI : Ocupado ? 1:si
O=df_ocupados[(df_ocupados['OCI']==1)]['FEX_C18'].sum()
print(f'Población Ocupada {O}')

Población Ocupada 23752952.66025585

In [126]:
#anexamos P640 TABLA OCUPADOS
df_ocupados = pd.merge(df_ocupados, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']],
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [128]:
#Personas ocupadas entre 20 y 25 años en Tolima

O2025T = df_ocupados_merged[(df_ocupados_merged['OCI']==1) & (df_ocupados_merged['P6040']>=20) & (df_ocupados_merged['P6040']<=25) & (df_ocupados_merged['DPTO']==73)]['FEX_C18'].sum()

print(f'Personas ocupadas en el tolima entre los 20 - 25 años: {O2025T}')

Personas ocupadas en el tolima entre los 20 - 25 años: 63257.06760223999

In [129]:
# Porcentaje respecto a la población total

POR = (O2025T / PTT) * 100

print(f'Porcentaje que representan: {POR:.2f}%')

Porcentaje que representan: 4.48%

In [ ]:
# RESPUESTA = Para calcular el número de personas ocupadas entre 20 y 25 años en el departamento del Tolima usamos el código DPTO = 73. Posteriormente se seleccionaron las personas ocupadas (OCI = 1) y cuya edad está entre 20 y 25 años según la variable P6040. Finalmente se sumó el factor de expansión FEX_C18 para estimar el número total de personas en esta condición y se calculó el porcentaje que representan respecto a la población total del Tolima que fue de 4.48%.